### ISSUE TITLE
Can't Add Datetime Plugin

### ISSUE THREAD

**Issue by matthewdunk** [SeptemberHX/dde-top-panel#32]
Copying the datetime plugin to the appropriate folder does nothing.

**Comment by SeptemberHX** [comment]
Have you relaunched the dde-top-panel after copying the `*.so` file ?

**Comment by matthewdunk** [comment]
Yes, I did indeed.

**Comment by SeptemberHX** [comment]
Strange, It did work for me.

![image](https://user-images.githubusercontent.com/18042424/106593211-7dc73980-658b-11eb-9b98-d80ed95450f3.png)

Which folder did you put the `*.so` file in ? It should work after copying the file to `~/.local/lib/dde-top-panel/plugins`

**Comment by matthewdunk** [comment]
I tried copying it to both `~/.local/lib/dde-top-panel/plugins` and `/usr/lib/dde-top-panel/plugins`. Nothing happened. I am running 20.1 with GNU/Linux kernel 5.8 BTW.

**Comment by SeptemberHX** [comment]
Does other plugins work with dde-top-panel ? 

Please run dde-top-panel in terminal and paste the output.

**Comment by matthewdunk** [comment]
So I got it to work on a fresh installation with the latest ISO from the Deepin-- I installed the Top Panel and added the DateTime plugin without updating the system as I did before--and it worked although the time was very tiny. As for your question, yes the other plugins worked flawlessly whether or not I updated to the latest edition of Deepin.

**Comment by SeptemberHX** [comment]
Glad it works now, although I still cannot reproduce the problem with the latest update of Deepin OS :(

For the tiny size, it is caused by the smaller height of the panel comparing to the dde-dock. Maybe it is a good choice to use other datetime plugin instead of the default one since the default one is designed for the dde-dock

**Comment by matthewdunk** [comment]
Other one?

**Comment by SeptemberHX** [comment]
> Other one?
You can try the `dde-istate-menus` plugin:  https://github.com/SeptemberHX/dde-istate-menus/issues/15#issuecomment-744140906    Use the attached version in the issue instead of the release version.

Since it is not designed for datetime, it will show more widgets like CPU, RAM, and network usage. Just disable others as shown in the issue linked above
