### ISSUE TITLE
Feature request : Add Support for Media playback

### ISSUE THREAD

**Issue by Bearbobs** [SeptemberHX/dde-top-panel#8]
Hey,
Amazing project. It will be great if you can add a music controller like deepin-topbar package. 
I can also assist, if you need help
Regards.

**Comment by SeptemberHX** [comment]
Hi,

Glad to know you like the top panel !

I also love the music controller(based mpris2 if I understand correctly). However, I don't think it is a good idea to integrate the music controller into the panel. The plugin should be used instead since the panel has the same ability to load plugins as the dock (plugin area is on the right of the tray area).

Both the dock and the top panel can use the plugin version, which also benefits those who don't use the top panel.

The official team (linuxdeepin) has documented how to write a plugin for the dock, and of course it also works for the top panel: [How to write a plugin](https://github.com/linuxdeepin/dde-dock/blob/master/plugins/plugin-guide/plugins-developer-guide.md). It is written in Chinese only.

Regards.

**Comment by SeptemberHX** [comment]
I will close this issue because we should not implement the media controller in this repository.

However, if you want to implement a plugin and have some trouble to read the guide for creating a plugin, just comment in this issue. I can provide some help since I have created some plugins already. See [dde-pstate](https://github.com/SeptemberHX/dde-pstate), [dde-smart-dir](https://github.com/SeptemberHX/dde-smart-dir).
